# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'dependabot'
    ignore:
      # requires manual intervention since we are 15+ versions behind
      - dependency-name: '@udecode/plate'
      # should be upgrade together with eslint
      - dependency-name: 'eslint'
      - dependency-name: '@typescript-eslint/parser'
      - dependency-name: '@typescript-eslint/eslint-plugin'
      - dependency-name: 'eslint-plugin-import'
      - dependency-name: 'eslint-plugin-unused-imports'
